version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
    commit-message:
      prefix: "chore"  # Optional: Prefix for commit messages and pull request titles
      include: "scope"  # Optional: Include the scope of the update in commit messages and pull request titles

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
